### PR TITLE
fix broken errors

### LINKED ISSUE #64: Can't extract error after newest gesell upgrade
We do this manually, and there seems to be a change in the formant, so we fail, and get the `can't extract error` error.

https://github.com/encointer/encointer-js/blob/4dfb32aa2a6079abbd49859154ccb84aed480d07/packages/node-api/src/tx.ts#L83

### PR DESCRIPTION
**Pull request by pifragile**
* Closes #64

### CODE REVIEW

**Review by clangenb — COMMENTED** [review]
Your fix does not compile. Is this because the typedef from the dependency is incompatible with the updated data? If yes, I suggest adding a compiler annotation to ignore that error, and we will schedule an upgrade of the deps soon.

**Comment by pifragile** [comment]
yes that seems to be the case. is there any action necessary from my side concerning the upgrade?

**Comment by clangenb** [comment]
No, I don't think so.  As the happy flow is a matter of minutes, I might try it, and test compatibility with the encointer-app's webview.

**Review by clangenb — APPROVED** [review]
Nice! Thanks for the fix and the extra test!

**Pull request merged**
